#!/bin/bash
# ── Production Startup Script ─────────────────────────────────────────────────
# Run this on the production server: bash start-production.sh
# Starts both backend (FastAPI) and frontend (Next.js) pointing to this server.

SERVER_IP="5.189.144.200"
BACKEND_PORT=8000
FRONTEND_PORT=3001

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/backend"
FRONTEND_DIR="$SCRIPT_DIR/frontend"

echo "=== QA Automation Agent — Production Start ==="
echo "Server   : $SERVER_IP"
echo "Backend  : http://$SERVER_IP:$BACKEND_PORT"
echo "Frontend : http://$SERVER_IP:$FRONTEND_PORT"
echo ""

# ── Write production frontend env ────────────────────────────────────────────
cat > "$FRONTEND_DIR/.env.local" <<EOF
# Auto-generated by start-production.sh — do not edit manually
NEXT_PUBLIC_API_URL=http://$SERVER_IP:$BACKEND_PORT
NEXT_PUBLIC_WS_URL=ws://$SERVER_IP:$BACKEND_PORT
EOF
echo "[frontend] .env.local written → API=$SERVER_IP:$BACKEND_PORT"

# ── Write production backend env extras ──────────────────────────────────────
# Only add ALLOWED_ORIGINS if not already set
if ! grep -q "^ALLOWED_ORIGINS=" "$BACKEND_DIR/.env" 2>/dev/null; then
    echo "ALLOWED_ORIGINS=http://$SERVER_IP:$FRONTEND_PORT,http://$SERVER_IP:$BACKEND_PORT,http://$SERVER_IP" \
        >> "$BACKEND_DIR/.env"
    echo "[backend]  ALLOWED_ORIGINS added to .env"
fi

# ── Start backend ─────────────────────────────────────────────────────────────
echo ""
echo "[backend]  Starting FastAPI on port $BACKEND_PORT ..."
cd "$BACKEND_DIR"
nohup python -m uvicorn app.main:app --host 0.0.0.0 --port $BACKEND_PORT > /tmp/backend.log 2>&1 &
BACKEND_PID=$!
echo "[backend]  PID $BACKEND_PID  |  logs: /tmp/backend.log"

sleep 2

# ── Start frontend ────────────────────────────────────────────────────────────
echo "[frontend] Starting Next.js on port $FRONTEND_PORT ..."
cd "$FRONTEND_DIR"
nohup npm run dev -- --port $FRONTEND_PORT > /tmp/frontend.log 2>&1 &
FRONTEND_PID=$!
echo "[frontend] PID $FRONTEND_PID  |  logs: /tmp/frontend.log"

echo ""
echo "=== Started ==="
echo "Open: http://$SERVER_IP:$FRONTEND_PORT"
echo ""
echo "To stop:  kill $BACKEND_PID $FRONTEND_PID"
echo "To view logs:"
echo "  tail -f /tmp/backend.log"
echo "  tail -f /tmp/frontend.log"
