"use client"

import { useState, useRef, useEffect } from "react"
import { useRouter } from "next/navigation"
import { flowAgentApi, diskFlowsApi } from "@/lib/api"
import { Sidebar } from "@/components/layout/sidebar"
import { Header } from "@/components/layout/header"
import {
  Send, Loader2, Save, Play, Copy, Check, Sparkles, Bot, User
} from "lucide-react"
import { cn } from "@/lib/utils"

type Message = {
  role: "user" | "assistant"
  text: string
  flow?: { name: string; steps: string[] }
  flowJson?: string
  usedLlm?: boolean
}

export default function FlowAgentPage() {
  const router = useRouter()
  const bottomRef  = useRef<HTMLDivElement>(null)
  const inputRef   = useRef<HTMLTextAreaElement>(null)

  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      text: "Hi! Describe your automation flow in plain English and I'll convert it into a clean JSON flow you can save and run.\n\nFor example:\n\"Login to the COS portal, search for subscriber 299230026, note the balance, then topup 200 kr and verify the balance updated.\"",
    },
  ])
  const [input, setInput]       = useState("")
  const [flowName, setFlowName] = useState("")
  const [loading, setLoading]   = useState(false)
  const [saved, setSaved]       = useState<string | null>(null)
  const [copied, setCopied]     = useState<string | null>(null)
  const [saveError, setSaveError] = useState("")

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [messages, loading])

  const send = async () => {
    const text = input.trim()
    if (!text || loading) return

    const userMsg: Message = { role: "user", text }
    setMessages(prev => [...prev, userMsg])
    setInput("")
    setLoading(true)
    setSaveError("")

    try {
      const { data } = await flowAgentApi.chat(text, flowName)
      const assistantMsg: Message = {
        role: "assistant",
        text: data.used_llm
          ? `Here's your flow (generated by ${getModelName()}):`
          : "Here's your flow (built from your description using the step parser):",
        flow: data.flow,
        flowJson: data.flow_json,
        usedLlm: data.used_llm,
      }
      setMessages(prev => [...prev, assistantMsg])
      if (!flowName && data.flow?.name) setFlowName(data.flow.name)
    } catch (e: any) {
      setMessages(prev => [
        ...prev,
        { role: "assistant", text: `Error: ${e?.response?.data?.detail || e.message}` },
      ])
    } finally {
      setLoading(false)
    }
  }

  const getModelName = () => "qwen2.5:7b"

  const onKey = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault()
      send()
    }
  }

  const copyJson = (json: string, id: string) => {
    navigator.clipboard.writeText(json)
    setCopied(id)
    setTimeout(() => setCopied(null), 2000)
  }

  const saveFlow = async (flow: { name: string; steps: string[] }, json: string) => {
    setSaveError("")
    setSaved(null)
    try {
      await diskFlowsApi.create(flow.name || flowName || "Untitled Flow", json, "json")
      setSaved(flow.name)
    } catch (e: any) {
      setSaveError(e?.response?.data?.detail || "Failed to save")
    }
  }

  const saveAndRun = async (flow: { name: string; steps: string[] }, json: string) => {
    setSaveError("")
    try {
      const { data } = await diskFlowsApi.create(flow.name || flowName || "Untitled Flow", json, "json")
      const { data: exec } = await diskFlowsApi.run(data.id)
      router.push(`/execution/${exec.id}`)
    } catch (e: any) {
      setSaveError(e?.response?.data?.detail || "Failed to run")
    }
  }

  return (
    <div className="flex min-h-screen bg-black">
      <Sidebar />
      <div className="flex-1 flex flex-col h-screen">
        <Header title="Flow Agent" />

        {/* Flow name bar */}
        <div className="border-b border-white/10 px-6 py-3 flex items-center gap-3">
          <Sparkles className="w-4 h-4 text-white/30 shrink-0" />
          <input
            value={flowName}
            onChange={e => setFlowName(e.target.value)}
            placeholder="Flow name (optional — extracted automatically)"
            className="flex-1 bg-transparent text-white/70 text-sm placeholder-white/20
                       focus:outline-none focus:text-white transition-colors"
          />
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto px-6 py-6 space-y-6">
          {messages.map((msg, i) => (
            <div key={i} className={cn("flex gap-3", msg.role === "user" ? "justify-end" : "justify-start")}>

              {msg.role === "assistant" && (
                <div className="w-7 h-7 rounded-full bg-white/10 flex items-center justify-center shrink-0 mt-0.5">
                  <Bot className="w-4 h-4 text-white/60" />
                </div>
              )}

              <div className={cn("max-w-2xl space-y-3", msg.role === "user" ? "items-end flex flex-col" : "")}>
                {/* Bubble */}
                <div className={cn(
                  "rounded-2xl px-4 py-3 text-sm whitespace-pre-wrap",
                  msg.role === "user"
                    ? "bg-white text-black rounded-br-sm"
                    : "bg-white/5 border border-white/10 text-white/80 rounded-bl-sm"
                )}>
                  {msg.text}
                </div>

                {/* Generated flow */}
                {msg.flow && msg.flowJson && (
                  <div className="w-full border border-white/10 rounded-xl overflow-hidden">
                    {/* Flow header */}
                    <div className="flex items-center justify-between px-4 py-2.5 bg-white/5 border-b border-white/10">
                      <div className="flex items-center gap-2">
                        <span className="text-white/60 text-xs font-mono">{msg.flow.name}</span>
                        <span className="text-white/25 text-xs">·</span>
                        <span className="text-white/30 text-xs">{msg.flow.steps.length} steps</span>
                        {msg.usedLlm && (
                          <span className="text-white/25 text-xs ml-1">· via {getModelName()}</span>
                        )}
                      </div>
                      <button
                        onClick={() => copyJson(msg.flowJson!, `${i}`)}
                        className="flex items-center gap-1.5 text-white/30 hover:text-white/70 transition-colors text-xs"
                      >
                        {copied === `${i}` ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                        {copied === `${i}` ? "Copied" : "Copy"}
                      </button>
                    </div>

                    {/* Steps preview */}
                    <div className="px-4 py-3 space-y-1 max-h-64 overflow-y-auto">
                      {msg.flow.steps.map((step, si) => (
                        <div key={si} className="flex items-start gap-2.5 text-xs">
                          <span className="text-white/20 font-mono w-5 shrink-0 pt-0.5 text-right">{si + 1}</span>
                          <span className={cn(
                            "text-white/60",
                            step === "SS" && "text-white/30 italic",
                            step.startsWith("Navigate") && "text-blue-400/70",
                            step.startsWith("Verify") && "text-green-400/70",
                          )}>
                            {step}
                          </span>
                        </div>
                      ))}
                    </div>

                    {/* Action buttons */}
                    <div className="flex items-center gap-2 px-4 py-3 border-t border-white/10 bg-white/[0.02]">
                      <button
                        onClick={() => saveFlow(msg.flow!, msg.flowJson!)}
                        className="flex items-center gap-1.5 bg-white/10 hover:bg-white/15 border border-white/10
                                   text-white/70 hover:text-white text-xs font-medium px-3 py-1.5 rounded-lg transition-all"
                      >
                        <Save className="w-3.5 h-3.5" />
                        Save Flow
                      </button>
                      <button
                        onClick={() => saveAndRun(msg.flow!, msg.flowJson!)}
                        className="flex items-center gap-1.5 bg-white text-black text-xs font-medium
                                   px-3 py-1.5 rounded-lg hover:bg-white/90 transition-all"
                      >
                        <Play className="w-3.5 h-3.5" />
                        Save & Run
                      </button>
                    </div>
                  </div>
                )}
              </div>

              {msg.role === "user" && (
                <div className="w-7 h-7 rounded-full bg-white/10 flex items-center justify-center shrink-0 mt-0.5">
                  <User className="w-4 h-4 text-white/60" />
                </div>
              )}
            </div>
          ))}

          {loading && (
            <div className="flex gap-3 justify-start">
              <div className="w-7 h-7 rounded-full bg-white/10 flex items-center justify-center shrink-0">
                <Bot className="w-4 h-4 text-white/60" />
              </div>
              <div className="bg-white/5 border border-white/10 rounded-2xl rounded-bl-sm px-4 py-3">
                <Loader2 className="w-4 h-4 animate-spin text-white/40" />
              </div>
            </div>
          )}

          {saved && (
            <div className="text-center text-green-400/70 text-xs">
              ✓ "{saved}" saved — <span
                className="underline cursor-pointer hover:text-green-400"
                onClick={() => router.push("/flows")}
              >view in Flows</span>
            </div>
          )}

          {saveError && (
            <div className="text-center text-red-400/70 text-xs">{saveError}</div>
          )}

          <div ref={bottomRef} />
        </div>

        {/* Input bar */}
        <div className="border-t border-white/10 px-6 py-4">
          <div className="flex gap-3 items-end">
            <textarea
              ref={inputRef}
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={onKey}
              rows={3}
              disabled={loading}
              placeholder="Describe your flow... e.g. 'Login to COS, search for customer 299230026, top up 200 kr and verify the balance updated'"
              className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white text-sm
                         placeholder-white/20 focus:outline-none focus:border-white/25 transition-colors
                         resize-none disabled:opacity-50"
            />
            <button
              onClick={send}
              disabled={loading || !input.trim()}
              className="flex items-center justify-center w-10 h-10 bg-white text-black rounded-xl
                         hover:bg-white/90 transition-all disabled:opacity-30 shrink-0 mb-0.5"
            >
              {loading
                ? <Loader2 className="w-4 h-4 animate-spin" />
                : <Send className="w-4 h-4" />
              }
            </button>
          </div>
          <p className="text-white/20 text-xs mt-2 pl-1">Enter to send · Shift+Enter for new line</p>
        </div>
      </div>
    </div>
  )
}
